// app/layout.js
import Link from 'next/link'; // Los <a href=""/> de next.js, ésta es la etiqueta que usaremos
import Image from 'next/image';
import "./globals.css";
import { Roboto } from 'next/font/google';

// Configuramos la fuente
const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '700'], // Puedes añadir más si los necesitas
  variable: '--font-roboto', // Opcional para usar con Tailwind o CSS
});


export const metadata = {
  title: "My App Fabrica de Coches",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="es">
      <body  className="font-courier bg-gray-100 flex h-screen">
        {/* BARRA LATERAL (Sidebar) - Siempre visible */}
        <nav className="w-64 bg-rose-50 text-black p-6 flex flex-col gap-4">
          <h2 className="text-2xl font-bold mb-8 text-blue-400">⚙️ AutoFabrik</h2>

          {/* Usamos <Link> para navegación instantánea */}
          <Link href="/" className="hover:text-blue-300 transition">Inicio</Link>
          <Link href="/produccion" className="hover:text-blue-300 transition">Línea de Producción</Link>
          <Link href="/logistica" className="hover:text-blue-300 transition">Logística y Almacén</Link>

          <div className="mt-auto text-xs text-slate-500">

            <Image
              width="100"
              height={100}
              src="https://i.blogs.es/3f1031/mercedes-vitoria-02/1366_2000.jpeg"
              alt='operario trabajando en la producción de un coche Mercedes'
              className="rounded-lg shadow-2xl w-sm"
            />
            Planta Vitoria-Gasteiz v2.0
          </div>
        </nav>

        {/* CONTENIDO DINÁMICO - Aquí es donde cambian las "salas" */}
        <main className="flex-1 p-10 overflow-y-auto">
          {/* children es la página en cuestión que utilice este layout*/}
          {children}
        </main>
      </body>
    </html>
  );
}
